import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "../component/header/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden overflow-y-hidden`}
      >
        <div className="relative w-full h-screen overflow-x-hidden overflow-y-hidden">
          {/* Header on top */}
          <div  className="absolute top-0 left-0 w-full z-10">
          <Header />
          </div>

          {/* Children in the background */}
          <div className="">{children}</div>
        </div>
      </body>
    </html>
  );
}
